### ISSUE TITLE
Cannot Compile in Adruino IDE Ubuntu

### ISSUE THREAD

**Issue by jfisher4** [BCLab-UNM/Swarmathon-Arduino#1]
I just noticed the new version of code. I tried to compile and upload to a rover and this is the error I got.

Swarmathon_Arduino.ino: In function ‘void update()’:
Swarmathon_Arduino.ino:178:42: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:178:42: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:179:42: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:179:42: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:180:42: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:180:42: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:181:39: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:181:39: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:182:39: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:182:39: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:183:39: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:183:39: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:184:34: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:184:34: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:185:34: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:185:34: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:186:34: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:186:34: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:187:27: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:187:27: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:188:27: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:188:27: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:189:31: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:189:31: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:190:28: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:190:28: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:191:28: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:191:28: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:192:32: error: call of overloaded ‘String(float&)’ is ambiguous
Swarmathon_Arduino.ino:192:32: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:193:38: error: call of overloaded ‘String(float)’ is ambiguous
Swarmathon_Arduino.ino:193:38: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:194:40: error: call of overloaded ‘String(float)’ is ambiguous
Swarmathon_Arduino.ino:194:40: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^
Swarmathon_Arduino.ino:195:39: error: call of overloaded ‘String(float)’ is ambiguous
Swarmathon_Arduino.ino:195:39: note: candidates are:
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/Print.h:26:0,
                 from /usr/share/arduino/hardware/arduino/cores/arduino/Stream.h:26,
                 from /usr/share/arduino/libraries/Wire/Wire.h:26,
                 from Swarmathon_Arduino.ino:6:
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:70:11: note: String::String(long unsigned int, unsigned char)
  explicit String(unsigned long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:69:11: note: String::String(long int, unsigned char)
  explicit String(long, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:68:11: note: String::String(unsigned int, unsigned char)
  explicit String(unsigned int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:67:11: note: String::String(int, unsigned char)
  explicit String(int, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:66:11: note: String::String(unsigned char, unsigned char)
  explicit String(unsigned char, unsigned char base=10);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:65:11: note: String::String(char)
  explicit String(char c);
           ^
/usr/share/arduino/hardware/arduino/cores/arduino/WString.h:60:2: note: String::String(const String&)
  String(const String &str);
  ^

Thanks,

Ryan

**Comment by jhecker** [comment]
Ryan,

Can you please tell me what version of the Arduino IDE you're using?  If you open the IDE, you should see the version number on the title bar.

I'm guessing that your version is 1.0.5, which is the (outdated) version of the application available in Aptitude. The String library has since been updated, and the errors you're getting have now been resolved -- check out the newest version of the IDE (1.6.8) on the [Arduino website](https://www.arduino.cc/en/Main/Software).

If you consult the recent [IMU calibration video](http://nasaswarmathon.com/qa-forum/?p=post%2Fcalibrating-the-imu-tutorial-8058934%3Fpid%3D1291783777) that was posted on the Q&A forum, you can follow Matthew's instructions for downloading and uncompressing the IDE from an alternative link via the command line.

**Comment by jfisher4** [comment]
Yes that is the version I am using, I will update it now. Thanks!

**Comment by jhecker** [comment]
Excellent -- I'll close the issue then.
